### ISSUE TITLE
Admin panel- All users

### ISSUE THREAD

**Issue by zarnab87** [dht64/laravel_lavina-erp#14]
(2/2) ErrorException
Call to a member function diffForHumans() on null (View: C:\xampp\htdocs\laravel_lavina-erp-master\resources\views\admin\users\index.blade.php)

This exception occurs when I'm trying to view All users.

**Comment by dht64** [comment]
Hi Zarnab87,
Found a bug in user migration table that the 'created_at' and 'updated_at' columns are null. You could fix this by update this info or refresh the migration and use available seed tables instead (php artisan db:seed).
