### ISSUE TITLE
After installing, I have a message, Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by gena-thunderstrucksales** [dht64/laravel_lavina-erp#16]
<img width="596" alt="Screen Shot 2020-11-09 at 9 30 24 AM" src="https://user-images.githubusercontent.com/71281284/98561529-9d8de080-226e-11eb-8ec7-c05836c60f2c.png">

**Comment by dht64** [comment]
Hi, 
Make sure you follow correctly installation steps as mentioned in the homepage. Or could refer to this topic in stackoverflow https://stackoverflow.com/questions/28893710/whoops-looks-like-something-went-wrong-laravel-5-0.

**Comment by gena-thunderstrucksales** [comment]
Ok, thanks i will try to figure out it.
